apiVersion: batch/v1
kind: Job
metadata:
  name: client
spec:
  template:
    spec:
      containers:
      - name: client
        image: ghcr.io/gaebaljadl/client:latest
      restartPolicy: Never
  backoffLimit: 4